CREATE DATABASE IF NOT EXISTS rupoi;
USE rupoi;

DROP TABLE IF EXISTS stathmos;
CREATE TABLE IF NOT EXISTS stathmos(
kodikos VARCHAR(25),
onoma VARCHAR(25),
geogr_mikos FLOAT( 10, 6 ) NOT NULL,
geogr_platos FLOAT( 10, 6 ) NOT NULL,
PRIMARY KEY(kodikos)
);

DROP TABLE IF EXISTS ripos;
CREATE TABLE IF NOT EXISTS ripos(
kod_stathmou VARCHAR(25),
eidos VARCHAR(25),
PRIMARY KEY(kod_stathmou),
CONSTRAINT YO FOREIGN KEY(kod_stathmou) REFERENCES stathmos(kodikos) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS daily;
CREATE TABLE IF NOT EXISTS daily(
kodikos VARCHAR(25),
eidos_ripou VARCHAR(25),
imerominia DATE NOT NULL,
t00 FLOAT(5),
t01 FLOAT(5),
t02 FLOAT(5),
t03 FLOAT(5),
t04 FLOAT(5), 
t05 FLOAT(5),
t06 FLOAT(5),
t07 FLOAT(5),
t08 FLOAT(5),
t09 FLOAT(5),
t10 FLOAT(5),
t11 FLOAT(5),
t12 FLOAT(5),
t13 FLOAT(5),
t14 FLOAT(5),
t15 FLOAT(5),
t16 FLOAT(5),
t17 FLOAT(5),
t18 FLOAT(5),
t19 FLOAT(5),
t20 FLOAT(5),
t21 FLOAT(5),
t22 FLOAT(5),
t23 FLOAT(5),
PRIMARY KEY(kodikos,imerominia),
-- CONSTRAINT YOO FOREIGN KEY(eidos_ripou) REFERENCES ripos(eidos) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT YOOO FOREIGN KEY(kodikos) REFERENCES ripos(kod_stathmou) ON DELETE CASCADE ON UPDATE CASCADE
);

